---
name: File-Copy-Vigilant
version: 1.01
author:
  - 'Anthony Kilna <anthony@kilna.com>'
abstract: Copy and move files with verification and retries
license: perl
requires:
  Digest::MD5::File: 0
  File::Compare: 0
  File::Copy: 0
  perl: 5.6.0
build_requires:
  Data::Dumper: 0
  File::Temp: 0
  FindBin: 0
  IO::File: 0
  Test::More: 0
provides:
  File::Copy::Vigilant:
    file: lib/File/Copy/Vigilant.pm
    version: 1.01
generated_by: Module::Build version 0.26
